version: 2
updates:
  - package-ecosystem: maven
    directory: /
    schedule:
      interval: daily
  - package-ecosystem: maven
    directory: maven/config
    schedule:
      interval: daily
  - package-ecosystem: maven
    directory: maven/config/iar
    schedule:
      interval: daily
  - package-ecosystem: maven
    directory: maven/config/test
    schedule:
      interval: daily
  - package-ecosystem: maven
    directory: maven/image-validation
    schedule:
      interval: daily
 
